deeptrading/deeptrading/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('django.contrib.auth.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

deeptrading/main/urls.py
from django.urls import path
from main import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'main'

urlpatterns = [
#	Main Page
    path('', views.MainView, name='main'),
#	LogIn
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
#	LogOut
    path('logout/',auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
#	SignUp/register
    path('signup/', views.RegView, name='signup'),
#	password change urls set
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_change_form.html', success_url='/users/password_change_done'), name='password_change'),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'), name='password_change_done'),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='password_reset_form.html', email_template_name='password_reset_email.html', subject_template_name='password_reset_subject.txt', success_url='/users/password_reset_done/', from_email='contact@deeptrading.info'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path("password_reset_confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', success_url='/users/password_reset_complete/'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),


]

deeptrading/main/models.py
from django.db import models

# Create your models here.
class Stats(models.Model):
    temperature = models.fields.FloatField()
    humidity = models.fields.FloatField()

    def __str__(self):
        return f'Temp = {self.temperature} and Humidity={self.humidity}'

deeptrading/main/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login as do_login
from django.contrib.auth import logout as do_logout
from main.functions.Manage_Databes import Manage_Database
import datetime

# Create your views here.
# -*- coding: utf-8 -*-



# Create your views here.

#MAIN PAGE:
def MainView(request):
	#si estamos identificados devolvemos la portada
#	u=True
	boton = {'stock_name':'AAPL'}
	if request.user.is_authenticated:
		db = Manage_Database()
		start_time = datetime.datetime(2020, 9, 21).strftime('%Y-%m-%d')
		end_time=datetime.datetime(2020, 9, 23).strftime('%Y-%m-%d')
		tokers = db.input_gaphs(stock_name='AAPL',start_time=start_time,end_time=end_time)
#	if u:
		context={"caca":"shit","2":"lil madafuka","hhh":"iii"}
#		tokers={'primero': {'Time':'2020-09-16 00:00:00','High': 116.0, 'Close': 112.12999725341797, 'Volume': 154679000, 'Open': 115.2300033569336, 'Low': 112.04000091552734}, 'segundo': {'Time':'2020-09-14 00:00:00','High': 115.93000030517578, 'Close': 115.36000061035156, 'Volume': 140150100, 'Open': 114.72000122070312, 'Low': 112.80000305175781}, 'tercero': {'Time':'2020-09-17 00:00:00','High': 112.19999694824219, 'Close': 110.33999633789062, 'Volume': 178011000, 'Open': 109.72000122070312, 'Low': 108.70999908447266}, 'cuarto': {'Time':'2020-09-10 00:00:00','High': 120.5, 'Close': 113.48999786376953, 'Volume': 182274400, 'Open': 120.36000061035156, 'Low': 112.5}, 5: {'Time':'2020-09-15 00:00:00','High': 118.83000183105469, 'Close': 115.54000091552734, 'Volume': 184642000, 'Open': 118.33000183105469, 'Low': 113.61000061035156}, 6: {'Time':'2020-09-18 00:00:00','High': 110.87999725341797, 'Close': 106.83999633789062, 'Volume': 286693600, 'Open': 110.4000015258789, 'Low': 106.08999633789062}, 7: {'Time':'2020-09-11 00:00:00','High': 115.2300033569336, 'Close': 112.0, 'Volume': 180860300, 'Open': 114.56999969482422, 'Low': 110.0}}
#		posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
		return render(request, 'main.html', tokers)
	else:
		return redirect('users:login')


#REGISTER PAGE
def RegView(request):
	#creamos el formulario de autenticacion vacio
	form = UserCreationForm()
	if request.method == 'POST':
		#añadimos los datos recibidos al formulario
		form = UserCreationForm(data=request.POST)
		#si el formulario es valido...
		if form.is_valid():
			#creamos la nueva cuenta de usuario
			user = form.save()
			#si el usuario se crea correctamente
			if user is not None:
				#hacemos login
				do_login(request, user)
				#y redireccionamos a la portada
				return redirect('MainView')
	#borrar campos de ayuda de formulario
	form.fields['username'].help_text = None
	form.fields['password1'].help_text = None
	form.fields['password2'].help_text = None
	return render(request, 'registration/signup.html',{'form':form})

#LOGIN PAGE
def LoginView(request):
	#Creamos el formulario de autenticación vacío
	form = AuthenticationForm()
	if request.method == 'POST':
		#Añadimos los datos recibidos al formulario
		form = AuthenticationForm(data=request.POST)
		#Si el formulario es valido...
		if form.is_valid():
			#Recuperamo las credenciales validadas
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			#Verificamos las credenciales
			user = authenticate(username=username, password=password)
			#si existe el usuario
			if user is not None:
				#hacemos login
				do_login(request, user)
				#Redireccionamos a la portada
				return redirect('MainView')
	#Si llegamos al final renderizamos el formulario
	return render(request, 'registration/login.html', {'form':form})

#LOGOUT PAGE
def LogoutView(request):
	#Finalizamos la sesion
	do_logout(request)
	return render(request, 'registration/logout.html')

deeptrading/templates/base.html
{% extends 'head.html' %}
{% block body %}

	<body>
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container">
				<div class='navbar-header'>
					<a href="{% url 'main:main' %}" class='navbar-brand'>DeepTrading</a>
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<!-- Code for the icon -->
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class='nav navbar-nav'>
						<li {% if section == 'Tokens' %} class='active'{% endif %}>
							<a href="{% url 'main:main' %}">Main</a>
						</li>
						<li {% if section == 'Otros' %} class='active'{% endif %}>
							<a href='#'>Other</a>
						</li>
						<li class="dropdown" {% if section == 'Otros2' %} class='active'{% endif %}>
							<a href='#' class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="">Other2</a>
							<ul class="dropdown-menu">
								<li><a href="#">Choice1</a></li>
								<li><a href="#">Choice2</a></li>
								<li><a href="#">Choice3</a></li>
							</ul>
						</li>
					</ul>
				</div>
				<ul class="nav navbar-nav navbar-right">
					<li><a href="#">Profile bar</a> </li>
				</ul>
			</div>
		</nav>
		<div class="container">
<!--			{% if request.user.is_authenticated %}-->
<!--				<span>jiji</span>-->
<!--			{% endif %}-->
			<div class="jumbotron">
				<h1> DeepTrading</h1>
				<h2>Best Fintech Website Ever!</h2>
				<p>
					{% if request.user.is_authenticated %}
						Hello {{ request.user.username }}!
						<a href='{% url 'main:logout' %}'>Logout</a>
					{% else %}
						Hello Anonimous User, please login
						<a href='{% url 'main:login' %}'>Login</a>
					{% endif %}
				</p>
			</div>
		</div>
		<div class='container'>
			{% block content %}
			{% endblock %}
		</div>
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	</body>
{% endblock %}

deeptrading/templates/head.html
<!DOCTYPE html>
<html lang='en'>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>
			{% block title %}DeepTrading{% endblock %}
		</title>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/luxon@1.24.1"></script>
		<script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.0-alpha/dist/Chart.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-luxon@0.2.1"></script>
		{% load static %}
		<script src="{% static 'deeptrading/chartjs-chart-financial.js' %}" type="text/javascript"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'deeptrading/style.css' %}">
<!--		<link rel="icon" href="./favicon.ico"/>-->

	</head>
	{% block body %}
	{% endblock %}
</html>

deeptrading/templates/main.html
{% extends 'base.html' %}

{% block title %} DeepTrading {% endblock %}

{% block content %}
	<div class="container">
		<div class="container" style="width:1000px">
<!--			<script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.0-alpha/dist/Chart.js"></script>-->
			<canvas id="chart"></canvas>
		</div>
		<div>
			Bar Type:
			<select id="type">
				<option value="candlestick" selected>Candlestick</option>
				<option value="ohlc">OHLC</option>
			</select>
			Scale Type:
			<select id="scale-type">
				<option value="linear" selected>Linear</option>
				<option value="logarithmic">Logarithmic</option>
			</select>
			Color Scheme:
			<select id="color-scheme">
				<option value="muted" selected>Muted</option>
				<option value="neon">Neon</option>
			</select>
			Border:
			<select id="border">
				<option value="true" selected>Yes</option>
				<option value="false">No</option>
			</select>
			<button id="update">Update</button>
			<button id="randomizeData">Randomize Data</button>
		</div>
		<div> <p>{{ primero }} {{ caca }}</p> aqui deberia haber aparecido algo</div>
		{% load static %}
<!--		<script type="text/javascript" src="{% static 'deeptrading/index.js' %}"></script>-->
<!--		<script>
			var barCount = 60;
			var initialDateStr = '01 Apr 2017 00:00 Z';

			var ctx = document.getElementById('chart').getContext('2d');
			ctx.canvas.width = 1000;
			ctx.canvas.height = 250;
			var chart = new Chart(ctx, {
				type: 'candlestick',
				data: {
					datasets: [{
						label: 'CHRT - Chart.js Corporation',
						data: {{ primero }}
					}]
				}
			});

			var update = function() {
				var dataset = chart.config.data.datasets[0];

				// candlestick vs ohlc
				var type = document.getElementById('type').value;
				dataset.type = type;

				// linear vs log
				var scaleType = document.getElementById('scale-type').value;
				chart.config.options.scales.y.type = scaleType;

				// color
				var colorScheme = document.getElementById('color-scheme').value;
				if (colorScheme === 'neon') {
					dataset.color = {
						up: '#01ff01',
						down: '#fe0000',
						unchanged: '#999',
					};
				} else {
					delete dataset.color;
				}

				// border
				var border = document.getElementById('border').value;
				var defaultOpts = Chart.defaults.elements[type];
				if (border === 'true') {
					dataset.borderColor = defaultOpts.borderColor;
				} else {
					dataset.borderColor = {
						up: defaultOpts.color.up,
						down: defaultOpts.color.down,
						unchanged: defaultOpts.color.up
					};
				}

				chart.update();
			};

			document.getElementById('update').addEventListener('click', update);

		</script>-->
		<script>var barCount = 60;
var initialDateStr = '01 Apr 2017 00:00 Z';

var ctx = document.getElementById('chart').getContext('2d');
ctx.canvas.width = 1000;
ctx.canvas.height = 250;
var chart = new Chart(ctx, {
	type: 'candlestick',
	data: {
		datasets: [{
			label: 'CHRT - Chart.js Corporation',
			data: getRandomData(initialDateStr, barCount)
		}]
	}
});

var getRandomInt = function(max) {
	return Math.floor(Math.random() * Math.floor(max));
};

function randomNumber(min, max) {
	return Math.random() * (max - min) + min;
}

function randomBar(date, lastClose) {
	var open = randomNumber(lastClose * 0.95, lastClose * 1.05).toFixed(2);
	var close = randomNumber(open * 0.95, open * 1.05).toFixed(2);
	var high = randomNumber(Math.max(open, close), Math.max(open, close) * 1.1).toFixed(2);
	var low = randomNumber(Math.min(open, close) * 0.9, Math.min(open, close)).toFixed(2);
	return {
		t: date.valueOf(),
		o: open,
		h: high,
		l: low,
		c: close
	};

}

function getRandomData(dateStr, count) {
	var date = luxon.DateTime.fromRFC2822(dateStr);
	var data = [randomBar(date, 30)];
	while (data.length < count) {
		date = date.plus({days: 1});
		if (date.weekday <= 5) {
			data.push(randomBar(date, data[data.length - 1].c));
		}
	}
	console.log(data);
	return data;
}

var update = function() {
	var dataset = chart.config.data.datasets[0];

	// candlestick vs ohlc
	var type = document.getElementById('type').value;
	dataset.type = type;

	// linear vs log
	var scaleType = document.getElementById('scale-type').value;
	chart.config.options.scales.y.type = scaleType;

	// color
	var colorScheme = document.getElementById('color-scheme').value;
	if (colorScheme === 'neon') {
		dataset.color = {
			up: '#01ff01',
			down: '#fe0000',
			unchanged: '#999',
		};
	} else {
		delete dataset.color;
	}

	// border
	var border = document.getElementById('border').value;
	var defaultOpts = Chart.defaults.elements[type];
	if (border === 'true') {
		dataset.borderColor = defaultOpts.borderColor;
	} else {
		dataset.borderColor = {
			up: defaultOpts.color.up,
			down: defaultOpts.color.down,
			unchanged: defaultOpts.color.up
		};
	}

	chart.update();
};

document.getElementById('update').addEventListener('click', update);

document.getElementById('randomizeData').addEventListener('click', function() {
	chart.data.datasets.forEach(function(dataset) {
		dataset.data = getRandomData(initialDateStr, barCount);
	});
	update();
});</script>
		<script type="text/javascript" src="{% static 'deeptrading/chartjs-chart-financial.js' %}"></script>
		<div><span>{% for toker in tokers %} {{ toker }} {% endfor %}</span><span>{{ tokers.0 }}</span></div>
	</div>
{% endblock %}